# Generated by Django 2.2.5 on 2020-10-15 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('avenida', models.CharField(max_length=50)),
                ('no_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.IntegerField()),
                ('otra_especificacion', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_raza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name': 'vacuna',
                'verbose_name_plural': 'vacunas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recate', models.DateField(verbose_name='Fecha de Rescate')),
                ('nombre_mascota', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad_aprox', models.IntegerField(verbose_name='Edad')),
                ('color', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], default='M', max_length=1)),
                ('sena_particular', models.CharField(blank=True, max_length=200)),
                ('esterilizado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('imagen', models.ImageField(upload_to='mascotas')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('lugar_rescate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mascotas.Lugar')),
                ('medicamento', models.ManyToManyField(blank=True, to='mascotas.Medicamento')),
                ('raza', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mascotas.Raza')),
                ('vacuna', models.ManyToManyField(blank=True, to='mascotas.Vacuna')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas rescatadas',
            },
        ),
        migrations.CreateModel(
            name='Adoptar_Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion de mascota')),
                ('iadoptar', models.ImageField(upload_to='adopcion')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
            options={
                'verbose_name': 'Publicar Mascota',
                'verbose_name_plural': 'Publicar Mascota - Adopcion',
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_adopcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_adopcion', models.DateTimeField(auto_now_add=True)),
                ('nombres_adoptante', models.CharField(max_length=100)),
                ('apellidos_adoptante', models.CharField(max_length=100)),
                ('edad_adoptante', models.IntegerField(verbose_name='Edad')),
                ('dpi_adoptante', models.CharField(max_length=50)),
                ('direccion_adoptante', models.CharField(max_length=50)),
                ('telefono_adoptante', models.CharField(max_length=50)),
                ('redes_adoptante', models.CharField(max_length=50)),
                ('pregunta1', models.TextField(verbose_name='¿Cuál es la razón por la que busca adoptar un perro?')),
                ('pregunta2', models.TextField(verbose_name='¿Por qué le interesa esta mascota en específico?')),
                ('pregunta3', models.CharField(max_length=100, verbose_name='¿Tiene otros animales actualmente en casa?')),
                ('pregunta4', models.CharField(max_length=100, verbose_name='¿Está de acuerdo que se le visite periódicamente para dar seguimiento a la adopción, para ver el estado de salud y bienestar la mascota que desea adoptar?')),
                ('pregunta5', models.CharField(max_length=100, verbose_name='¿Estaría de acuerdo en notificar a la Asociación si tuviera cambio de dirección?')),
                ('pregunta6', models.CharField(max_length=100, verbose_name='¿Tiene espacio adecuado para la mascota?')),
                ('pregunta8', models.CharField(max_length=100, verbose_name='¿Quién será responsable de cubrir los gastos veterinarios, limpiar, cuidar y alimentar a la mascota que desea adoptar?')),
                ('pregunta9', models.CharField(max_length=100, verbose_name='¿Están de acuerdo todos los miembros de su familia en la adopción de una mascota?')),
                ('pregunta10', models.CharField(max_length=100, verbose_name='¿Está de acuerdo en castrar (en caso de ser hembra) a la mascota que desea adoptar, para evitar la reproducción animal y pagar la misma?')),
                ('pregunta11', models.CharField(max_length=100, verbose_name='¿Está consciente de que una mascota necesita alimentación adecuada, un lugar cómodo para descansar, vacunas anuales, gastos veterinarios, shampoos especiales y baños frecuentes?')),
                ('pregunta12', models.CharField(max_length=100, verbose_name='¿Sabe usted que un cachorro es travieso por naturaleza, puede romper zapatos, ropa, juguetes que se dejen descuidados a su alcance?')),
                ('pregunta13', models.CharField(max_length=100, verbose_name='¿Tiene usted el tiempo de entrenar a la mascota para que haga sus necesidades en algún lugar en específico?')),
                ('pregunta14', models.CharField(max_length=100, verbose_name='¿Sabe usted que hay enfermedades graves transmitidas por las garrapatas?, por lo que es necesario mantener a las mascotas libres de estas plagas.')),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
            options={
                'verbose_name': 'adopción',
                'verbose_name_plural': 'adoptar una Mascota',
            },
        ),
    ]
