# Generated by Django 2.2.5 on 2020-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20201015_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='no_casa',
        ),
        migrations.AlterField(
            model_name='adoptar_mascota',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Publicado?'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
